# USE THIS AT YOUR OWN RISK

PATH=$PATH:/usr/local/cuda/bin:/Applications/QGLE.app/Contents/bin
export LD_LIBRARY_PATH=/opt/local/lib:/usr/local/cuda/lib:${LD_LIBRARY_PATH}

# MacPorts Installer addition 
export PATH=/opt/local/bin:/opt/local/sbin:${HOME}/software/bin:${PATH}:/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin
export DYLD_LIBRARY_PATH=/usr/local/cuda/lib:~/software/lib:${DYLD_LIBRARY_PATH}
# Finished adapting your PATH environment variable for use with MacPorts.

alias ll='ls -l'
alias la='ls -la'
alias vmd='rlwrap /Applications/VMD\ 1.9.2.app/Contents/MacOS/startup.command'
export CLICOLOR=1
export LSCOLORS="gxfxcxdxbxegedabagacad"
#alias maverick='ssh USERNAME@maverick.tacc.utexas.edu'
#export VMDFILECHOOSER='FLTK'
#export HDF5_DISABLE_VERSION_CHECK=2
#export TCLLIB=/opt/local/lib/libtcl.dylib
#export TCLINC=/opt/local/include
#export TCL_INCLUDE_DIR=/opt/local/include
#export TCL_LIBRARY_DIR=/opt/local/lib
#export TK_INCLUDE_DIR=/opt/local/include
#export TK_LIBRARY_DIR=/opt/local/lib
#export PLUGINDIR=~/Projects/vmd/vmd/plugins
#export NUMPY_INCLUDE_DIR=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include
